### ISSUE TITLE
Install library through the makefile

### ISSUE THREAD

**Issue by lucywyman** [lucywyman/Senior-Project#11]
How does the teacher install external libraries locally through the makefile? Is this a thing they can already do?

**Comment by hennign** [comment]
Did Justin actually say he wanted this feature or was he just curious if it was possible? Andrew and I discussed it and it seems to us that it would be better to have th admin manually install requested packages. We should probably double check with Justin.

**Comment by lucywyman** [comment]
It was something I wrote down during our meeting? I would double check with him, but I don't think we'll fail if we don't do it.
